services:
  django_security_hunter:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_security_hunter:local
    working_dir: /app
    volumes:
      - ./:/app
    command: ["scan", "--project", "/app", "--format", "console"]

