services:
  djsecinspect:
    build:
      context: .
      dockerfile: Dockerfile
    image: djsecinspect:local
    working_dir: /app
    volumes:
      - ./:/app
    command: djsecinspect scan --project /app --format console

