services:
  django_security_hunter:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_security_hunter:local
    working_dir: /app
    volumes:
      - ./:/app
    command: django_security_hunter scan --project /app --format console

